#!/bin/bash

# Fix script for dashboard farms and nets showing 0 despite backend returning correct values

echo "=========================================="
echo "Dashboard Farms/Nets Display Fix"
echo "=========================================="
echo ""

echo "This script will:"
echo "1. Restart the web container to rebuild frontend"
echo "2. Clear browser caches"
echo ""
read -p "Press Enter to continue..."

# Step 1: Restart web container
echo ""
echo "Step 1: Restarting web container..."
echo "----------------------------------------"
docker compose restart web

echo ""
echo "Waiting 30 seconds for frontend to rebuild..."
sleep 30

echo ""
echo "=========================================="
echo "NEXT STEPS - DO THESE IN YOUR BROWSER:"
echo "=========================================="
echo ""
echo "1. CLEAR SERVICE WORKER (if using PWA):"
echo "   - Open DevTools (F12)"
echo "   - Go to 'Application' tab"
echo "   - Click 'Service Workers' in left sidebar"
echo "   - Click 'Unregister' for any service workers"
echo "   - Click 'Storage' in left sidebar"
echo "   - Click 'Clear site data' button"
echo ""
echo "2. HARD REFRESH THE PAGE:"
echo "   - Mac: Cmd + Shift + R"
echo "   - Windows/Linux: Ctrl + Shift + R"
echo ""
echo "3. CHECK THE CONSOLE:"
echo "   - Open DevTools (F12)"
echo "   - Go to 'Console' tab"
echo "   - You should see:"
echo "     'DEBUG: Received metrics data: {...}'"
echo "     'DEBUG: total_farm_sites = 1'"
echo "     'DEBUG: total_nets = 3'"
echo ""
echo "4. CHECK THE NETWORK TAB:"
echo "   - Open DevTools (F12)"
echo "   - Go to 'Network' tab"
echo "   - Refresh the page"
echo "   - Find the 'metrics' request"
echo "   - Click on it"
echo "   - Check the 'Response' tab"
echo "   - Verify total_farm_sites: 1 and total_nets: 3"
echo ""
echo "5. IF STILL SHOWING 0:"
echo "   - Close ALL browser tabs for localhost:3000"
echo "   - Close the browser completely"
echo "   - Reopen browser and go to http://localhost:3000"
echo "   - Login again"
echo ""
echo "=========================================="
echo "Web container restarted successfully!"
echo "Frontend should be rebuilding now."
echo "Follow the steps above to clear caches."
echo "=========================================="
