"""baseline_from_production

Revision ID: a1ca172ca9cc
Revises: f182c0f2b7ab
Create Date: 2025-11-29 15:08:44.464425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1ca172ca9cc'
down_revision: Union[str, Sequence[str], None] = 'f182c0f2b7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_alerts_alert_type'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_is_active'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_part_id'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_severity'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_warehouse_id'), table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    op.drop_index(op.f('ix_inventory_adjustments_adjustment_date'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_part_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_stocktake_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_warehouse_id'), table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.alter_column('customer_orders', 'shipped_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_inventory_warehouse_part'), table_name='inventory')
    op.drop_constraint(op.f('inventory_warehouse_id_part_id_key'), 'inventory', type_='unique')
    op.create_foreign_key(None, 'invitation_audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'machine_hours', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'machine_maintenance', 'users', ['performed_by_user_id'], ['id'])
    op.create_foreign_key(None, 'machine_maintenance', 'machines', ['machine_id'], ['id'])
    op.drop_index(op.f('idx_machines_customer'), table_name='machines')
    op.drop_column('machines', 'operational_status')
    op.drop_column('machines', 'year_manufactured')
    op.drop_column('machines', 'last_maintenance_date')
    op.drop_column('machines', 'maintenance_notes')
    op.drop_column('machines', 'installation_date')
    op.drop_column('machines', 'maintenance_status')
    op.drop_column('machines', 'machine_status')
    op.drop_column('machines', 'purchase_date')
    op.drop_column('machines', 'maintenance_cost')
    op.drop_column('machines', 'maintenance_interval_days')
    op.drop_column('machines', 'operator_name')
    op.drop_column('machines', 'status')
    op.drop_column('machines', 'hours_since_maintenance')
    op.drop_column('machines', 'technician_name')
    op.drop_column('machines', 'service_interval_hours')
    op.drop_column('machines', 'next_service_due')
    op.drop_column('machines', 'total_operating_hours')
    op.drop_column('machines', 'max_operating_hours')
    op.drop_column('machines', 'location')
    op.drop_column('machines', 'manufacturer')
    op.drop_column('machines', 'warranty_expiry_date')
    op.drop_column('machines', 'current_hours')
    op.drop_column('machines', 'last_service_date')
    op.drop_column('machines', 'notes')
    op.drop_column('machines', 'next_maintenance_date')
    op.drop_column('machines', 'machine_condition')
    op.drop_index(op.f('idx_organizations_name'), table_name='organizations')
    op.drop_constraint(op.f('organizations_name_key'), 'organizations', type_='unique')
    op.drop_index(op.f('unique_bossaqua'), table_name='organizations', postgresql_where="(organization_type = 'bossaqua'::organizationtype)")
    op.drop_index(op.f('unique_oraseas_ee'), table_name='organizations', postgresql_where="(organization_type = 'oraseas_ee'::organizationtype)")
    op.drop_column('organizations', 'country')
    op.create_foreign_key(None, 'part_order_items', 'warehouses', ['destination_warehouse_id'], ['id'])
    op.alter_column('parts', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('idx_parts_manufacturer'), table_name='parts', postgresql_where='(manufacturer IS NOT NULL)')
    op.drop_index(op.f('idx_parts_name_fulltext'), table_name='parts', postgresql_using='gin')
    op.drop_index(op.f('idx_parts_part_number'), table_name='parts')
    op.drop_index(op.f('idx_parts_type_proprietary'), table_name='parts')
    op.drop_constraint(op.f('parts_part_number_key'), 'parts', type_='unique')
    op.drop_column('parts', 'dimensions')
    op.drop_column('parts', 'warranty_period')
    op.drop_column('parts', 'serial_number')
    op.drop_column('parts', 'part_code')
    op.drop_column('parts', 'weight')
    op.drop_column('parts', 'color')
    op.drop_column('parts', 'manufacturer')
    op.drop_column('parts', 'material')
    op.drop_column('parts', 'supplier_part_number')
    op.drop_column('parts', 'category')
    op.create_foreign_key(None, 'security_events', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_stocktake_items_part_id'), table_name='stocktake_items')
    op.drop_index(op.f('ix_stocktake_items_stocktake_id'), table_name='stocktake_items')
    op.drop_constraint(op.f('stocktake_items_stocktake_id_fkey'), 'stocktake_items', type_='foreignkey')
    op.create_foreign_key(None, 'stocktake_items', 'stocktakes', ['stocktake_id'], ['id'])
    op.alter_column('stocktakes', 'status',
               existing_type=postgresql.ENUM('planned', 'in_progress', 'completed', 'cancelled', name='stocktakestatus'),
               type_=sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='stocktakestatusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'planned'::stocktakestatus"))
    op.drop_index(op.f('ix_stocktakes_scheduled_date'), table_name='stocktakes')
    op.drop_index(op.f('ix_stocktakes_status'), table_name='stocktakes')
    op.drop_index(op.f('ix_stocktakes_warehouse_id'), table_name='stocktakes')
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('creation', 'transfer', 'consumption', 'adjustment', name='transactiontype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_transactions_date'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_part'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_warehouse'), table_name='transactions')
    op.create_foreign_key(None, 'transactions', 'customer_orders', ['customer_order_id'], ['id'])
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_org_role'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_invited_by_user_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'invited_by_user_id')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'localization_preferences')
    op.drop_column('users', 'preferred_country')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'pending_email')
    op.drop_constraint(op.f('warehouses_organization_id_name_key'), 'warehouses', type_='unique')
    op.drop_column('warehouses', 'email')
    op.drop_column('warehouses', 'warehouse_type')
    op.drop_column('warehouses', 'contact_person')
    op.drop_column('warehouses', 'address')
    op.drop_column('warehouses', 'phone')
    op.drop_column('warehouses', 'capacity_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('capacity_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('warehouse_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('warehouses_organization_id_name_key'), 'warehouses', ['organization_id', 'name'], postgresql_nulls_not_distinct=False)
    op.add_column('users', sa.Column('pending_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_country', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('localization_preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('invited_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_invited_by_user_id_fkey'), 'users', 'users', ['invited_by_user_id'], ['id'])
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_org_role'), 'users', ['organization_id', 'role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_index(op.f('idx_transactions_warehouse'), 'transactions', ['from_warehouse_id', 'to_warehouse_id'], unique=False)
    op.create_index(op.f('idx_transactions_part'), 'transactions', ['part_id'], unique=False)
    op.create_index(op.f('idx_transactions_date'), 'transactions', ['transaction_date'], unique=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('creation', 'transfer', 'consumption', 'adjustment', name='transactiontype'),
               existing_nullable=False)
    op.create_index(op.f('ix_stocktakes_warehouse_id'), 'stocktakes', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_stocktakes_status'), 'stocktakes', ['status'], unique=False)
    op.create_index(op.f('ix_stocktakes_scheduled_date'), 'stocktakes', ['scheduled_date'], unique=False)
    op.alter_column('stocktakes', 'status',
               existing_type=sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='stocktakestatusenum'),
               type_=postgresql.ENUM('planned', 'in_progress', 'completed', 'cancelled', name='stocktakestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'planned'::stocktakestatus"))
    op.drop_constraint(None, 'stocktake_items', type_='foreignkey')
    op.create_foreign_key(op.f('stocktake_items_stocktake_id_fkey'), 'stocktake_items', 'stocktakes', ['stocktake_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_stocktake_items_stocktake_id'), 'stocktake_items', ['stocktake_id'], unique=False)
    op.create_index(op.f('ix_stocktake_items_part_id'), 'stocktake_items', ['part_id'], unique=False)
    op.drop_constraint(None, 'security_events', type_='foreignkey')
    op.add_column('parts', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('supplier_part_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('weight', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('warranty_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('dimensions', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('parts_part_number_key'), 'parts', ['part_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_parts_type_proprietary'), 'parts', ['part_type', 'is_proprietary'], unique=False)
    op.create_index(op.f('idx_parts_part_number'), 'parts', ['part_number'], unique=False)
    op.create_index(op.f('idx_parts_name_fulltext'), 'parts', [sa.literal_column("to_tsvector('english'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_parts_manufacturer'), 'parts', ['manufacturer'], unique=False, postgresql_where='(manufacturer IS NOT NULL)')
    op.alter_column('parts', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'part_order_items', type_='foreignkey')
    op.add_column('organizations', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('unique_oraseas_ee'), 'organizations', ['organization_type'], unique=True, postgresql_where="(organization_type = 'oraseas_ee'::organizationtype)")
    op.create_index(op.f('unique_bossaqua'), 'organizations', ['organization_type'], unique=True, postgresql_where="(organization_type = 'bossaqua'::organizationtype)")
    op.create_unique_constraint(op.f('organizations_name_key'), 'organizations', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_organizations_name'), 'organizations', ['name'], unique=False)
    op.add_column('machines', sa.Column('machine_condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('next_maintenance_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('last_service_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('current_hours', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('warranty_expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('manufacturer', sa.VARCHAR(length=255), server_default=sa.text("'BossAqua'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('max_operating_hours', sa.INTEGER(), server_default=sa.text('10000'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('total_operating_hours', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('next_service_due', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('service_interval_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('technician_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('hours_since_maintenance', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('operator_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('maintenance_interval_days', sa.INTEGER(), server_default=sa.text('90'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('maintenance_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('machine_status', sa.VARCHAR(length=50), server_default=sa.text("'operational'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('maintenance_status', sa.VARCHAR(length=50), server_default=sa.text("'up_to_date'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('installation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('maintenance_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('last_maintenance_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('year_manufactured', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('operational_status', sa.VARCHAR(length=50), server_default=sa.text("'running'::character varying"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_machines_customer'), 'machines', ['customer_organization_id'], unique=False)
    op.drop_constraint(None, 'machine_maintenance', type_='foreignkey')
    op.drop_constraint(None, 'machine_maintenance', type_='foreignkey')
    op.drop_constraint(None, 'machine_hours', type_='foreignkey')
    op.drop_constraint(None, 'invitation_audit_logs', type_='foreignkey')
    op.create_unique_constraint(op.f('inventory_warehouse_id_part_id_key'), 'inventory', ['warehouse_id', 'part_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_inventory_warehouse_part'), 'inventory', ['warehouse_id', 'part_id'], unique=False)
    op.alter_column('customer_orders', 'shipped_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity_change', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('previous_quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('new_quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adjusted_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('adjustment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('stocktake_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['adjusted_by_user_id'], ['users.id'], name=op.f('inventory_adjustments_adjusted_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('inventory_adjustments_part_id_fkey')),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktakes.id'], name=op.f('inventory_adjustments_stocktake_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('inventory_adjustments_transaction_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('inventory_adjustments_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_adjustments_pkey'))
    )
    op.create_index(op.f('ix_inventory_adjustments_warehouse_id'), 'inventory_adjustments', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_stocktake_id'), 'inventory_adjustments', ['stocktake_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_part_id'), 'inventory_adjustments', ['part_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_adjustment_date'), 'inventory_adjustments', ['adjustment_date'], unique=False)
    op.create_table('inventory_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_type', postgresql.ENUM('low_stock', 'stockout', 'expiring', 'expired', 'excess', 'discrepancy', name='inventoryalerttype'), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', 'critical', name='inventoryalertseverity'), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('inventory_alerts_part_id_fkey')),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('inventory_alerts_resolved_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('inventory_alerts_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_alerts_pkey'))
    )
    op.create_index(op.f('ix_inventory_alerts_warehouse_id'), 'inventory_alerts', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_severity'), 'inventory_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_part_id'), 'inventory_alerts', ['part_id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_is_active'), 'inventory_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_alert_type'), 'inventory_alerts', ['alert_type'], unique=False)
    # ### end Alembic commands ###
