"""baseline_schema_20260109_112922

Revision ID: ab2c1f16b0b3
Revises: a78bd1ac6e99
Create Date: 2026-01-09 09:29:22.755996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab2c1f16b0b3'
down_revision: Union[str, Sequence[str], None] = 'a78bd1ac6e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_expert_feedback_created_at'), table_name='expert_feedback')
    op.drop_index(op.f('idx_expert_feedback_expert_user_id'), table_name='expert_feedback')
    op.drop_index(op.f('idx_expert_feedback_message_id'), table_name='expert_feedback')
    op.drop_index(op.f('idx_expert_feedback_rating'), table_name='expert_feedback')
    op.drop_index(op.f('idx_expert_feedback_session_id'), table_name='expert_feedback')
    op.drop_index(op.f('idx_expert_feedback_type'), table_name='expert_feedback')
    op.drop_table('expert_feedback')
    op.drop_index(op.f('idx_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('stock_adjustments_backup')
    op.drop_index(op.f('ix_inventory_alerts_alert_type'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_is_active'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_part_id'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_severity'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_warehouse_id'), table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    op.drop_index(op.f('idx_support_tickets_created_at'), table_name='support_tickets')
    op.drop_index(op.f('idx_support_tickets_priority'), table_name='support_tickets')
    op.drop_index(op.f('idx_support_tickets_session_id'), table_name='support_tickets')
    op.drop_index(op.f('idx_support_tickets_status'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('idx_expert_knowledge_created_at'), table_name='expert_knowledge')
    op.drop_index(op.f('idx_expert_knowledge_machine_version'), table_name='expert_knowledge')
    op.drop_index(op.f('idx_expert_knowledge_verified'), table_name='expert_knowledge')
    op.drop_table('expert_knowledge')
    op.drop_index(op.f('idx_document_embeddings_chunk_index'), table_name='document_embeddings')
    op.drop_index(op.f('idx_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('idx_escalation_triggers_session_id'), table_name='escalation_triggers')
    op.drop_index(op.f('idx_escalation_triggers_triggered_at'), table_name='escalation_triggers')
    op.drop_index(op.f('idx_escalation_triggers_type'), table_name='escalation_triggers')
    op.drop_table('escalation_triggers')
    op.drop_index(op.f('idx_knowledge_documents_created_at'), table_name='knowledge_documents')
    op.drop_index(op.f('idx_knowledge_documents_language'), table_name='knowledge_documents')
    op.drop_index(op.f('idx_knowledge_documents_machine_models'), table_name='knowledge_documents', postgresql_using='gin')
    op.drop_index(op.f('idx_knowledge_documents_tags'), table_name='knowledge_documents', postgresql_using='gin')
    op.drop_index(op.f('idx_knowledge_documents_type'), table_name='knowledge_documents')
    op.drop_index(op.f('idx_knowledge_documents_updated_at'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.alter_column('ai_messages', 'sender',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='ai_message_sender'),
               type_=sa.Enum('user', 'assistant', 'system', name='aimessagesender'),
               existing_nullable=False)
    op.alter_column('ai_messages', 'message_type',
               existing_type=postgresql.ENUM('text', 'voice', 'image', 'diagnostic_step', 'escalation', name='ai_message_type'),
               type_=sa.Enum('text', 'voice', 'image', 'diagnostic_step', 'escalation', name='aimessagetype'),
               existing_nullable=False,
               existing_server_default=sa.text("'text'::ai_message_type"))
    op.drop_index(op.f('idx_ai_messages_created_at'), table_name='ai_messages')
    op.drop_index(op.f('idx_ai_messages_sender'), table_name='ai_messages')
    op.drop_index(op.f('idx_ai_messages_session_id'), table_name='ai_messages')
    op.alter_column('ai_sessions', 'status',
               existing_type=postgresql.ENUM('active', 'completed', 'escalated', 'abandoned', name='ai_session_status'),
               type_=sa.Enum('active', 'completed', 'escalated', 'abandoned', name='aisessionstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::ai_session_status"))
    op.drop_index(op.f('idx_ai_sessions_created_at'), table_name='ai_sessions')
    op.drop_index(op.f('idx_ai_sessions_machine_id'), table_name='ai_sessions')
    op.drop_index(op.f('idx_ai_sessions_status'), table_name='ai_sessions')
    op.drop_index(op.f('idx_ai_sessions_updated_at'), table_name='ai_sessions')
    op.drop_index(op.f('idx_ai_sessions_user_id'), table_name='ai_sessions')
    op.drop_constraint(op.f('ai_sessions_machine_id_fkey'), 'ai_sessions', type_='foreignkey')
    op.drop_constraint(op.f('ai_sessions_user_id_fkey'), 'ai_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'ai_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ai_sessions', 'machines', ['machine_id'], ['id'])
    op.drop_index(op.f('ix_checklist_translations_item_id'), table_name='checklist_item_translations')
    op.drop_index(op.f('ix_checklist_translations_language_code'), table_name='checklist_item_translations')
    op.alter_column('customer_orders', 'shipped_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_inventory_warehouse_part'), table_name='inventory')
    op.drop_constraint(op.f('inventory_warehouse_id_part_id_key'), 'inventory', type_='unique')
    op.create_foreign_key(None, 'invitation_audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'machine_hours', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'machine_maintenance', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'machine_maintenance', 'users', ['performed_by_user_id'], ['id'])
    op.drop_index(op.f('idx_machines_customer'), table_name='machines')
    op.drop_column('machines', 'machine_model')
    op.drop_column('machines', 'next_maintenance_date')
    op.drop_column('machines', 'service_interval_hours')
    op.drop_column('machines', 'notes')
    op.drop_column('machines', 'manufacturer')
    op.drop_column('machines', 'machine_condition')
    op.drop_column('machines', 'year_manufactured')
    op.drop_column('machines', 'total_operating_hours')
    op.drop_column('machines', 'location')
    op.drop_column('machines', 'operator_name')
    op.drop_column('machines', 'machine_status')
    op.drop_column('machines', 'technician_name')
    op.drop_column('machines', 'status')
    op.drop_column('machines', 'maintenance_notes')
    op.drop_column('machines', 'last_service_date')
    op.drop_column('machines', 'maintenance_interval_days')
    op.drop_column('machines', 'max_operating_hours')
    op.drop_column('machines', 'maintenance_status')
    op.drop_column('machines', 'operational_status')
    op.drop_column('machines', 'purchase_date')
    op.drop_column('machines', 'warranty_expiry_date')
    op.drop_column('machines', 'hours_since_maintenance')
    op.drop_column('machines', 'maintenance_cost')
    op.drop_column('machines', 'installation_date')
    op.drop_column('machines', 'last_maintenance_date')
    op.drop_column('machines', 'current_hours')
    op.drop_column('machines', 'next_service_due')
    op.alter_column('maintenance_checklist_completions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('maintenance_checklist_completions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('maintenance_checklist_completions_checklist_item_id_fkey'), 'maintenance_checklist_completions', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_checklist_completions', 'protocol_checklist_items', ['checklist_item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maintenance_executions', 'performed_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('maintenance_executions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('scheduled', 'in_progress', 'completed', 'partial', 'skipped', name='maintenanceexecutionstatus'),
               existing_nullable=True)
    op.alter_column('maintenance_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_execution_machine'), table_name='maintenance_executions')
    op.alter_column('maintenance_protocols', 'protocol_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('daily', 'weekly', 'scheduled', 'custom', name='protocoltype'),
               existing_nullable=False)
    op.alter_column('maintenance_protocols', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_protocols', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_protocol_type_model'), table_name='maintenance_protocols')
    op.alter_column('maintenance_reminders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'acknowledged', 'completed', 'dismissed', name='reminderstatus'),
               existing_nullable=True)
    op.alter_column('maintenance_reminders', 'acknowledged_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('maintenance_reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reminder_due_hours'), table_name='maintenance_reminders')
    op.drop_index(op.f('idx_reminder_machine_status'), table_name='maintenance_reminders')
    op.alter_column('organizations', 'country',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('GR', 'UK', 'NO', 'CA', 'NZ', 'TR', 'OM', 'ES', 'CY', 'SA', 'KSA', name='countrycode'),
               existing_nullable=True)
    op.drop_index(op.f('idx_organizations_name'), table_name='organizations')
    op.drop_constraint(op.f('organizations_name_key'), 'organizations', type_='unique')
    op.drop_index(op.f('unique_bossaqua'), table_name='organizations', postgresql_where="(organization_type = 'bossaqua'::organizationtype)")
    op.drop_index(op.f('unique_oraseas_ee'), table_name='organizations', postgresql_where="(organization_type = 'oraseas_ee'::organizationtype)")
    op.create_foreign_key(None, 'part_order_items', 'warehouses', ['destination_warehouse_id'], ['id'])
    op.drop_index(op.f('idx_part_videos_part_id'), table_name='part_videos')
    op.alter_column('parts', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('idx_parts_manufacturer'), table_name='parts', postgresql_where='(manufacturer IS NOT NULL)')
    op.drop_index(op.f('idx_parts_name_fulltext'), table_name='parts', postgresql_using='gin')
    op.drop_index(op.f('idx_parts_part_number'), table_name='parts')
    op.drop_index(op.f('idx_parts_type_proprietary'), table_name='parts')
    op.drop_constraint(op.f('parts_part_number_key'), 'parts', type_='unique')
    op.drop_column('parts', 'manufacturer')
    op.drop_column('parts', 'material')
    op.drop_column('parts', 'category')
    op.drop_column('parts', 'warranty_period')
    op.drop_column('parts', 'part_code')
    op.drop_column('parts', 'color')
    op.drop_column('parts', 'dimensions')
    op.drop_column('parts', 'weight')
    op.drop_column('parts', 'supplier_part_number')
    op.drop_column('parts', 'serial_number')
    op.alter_column('protocol_checklist_items', 'item_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('check', 'service', 'replacement', name='checklistitemtype'),
               existing_nullable=False)
    op.alter_column('protocol_checklist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_checklist_protocol'), table_name='protocol_checklist_items')
    op.drop_index(op.f('ix_protocol_translations_language_code'), table_name='protocol_translations')
    op.drop_index(op.f('ix_protocol_translations_protocol_id'), table_name='protocol_translations')
    op.create_foreign_key(None, 'security_events', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_stock_adjustment_items_part_id'), table_name='stock_adjustment_items')
    op.drop_index(op.f('ix_stock_adjustment_items_stock_adjustment_id'), table_name='stock_adjustment_items')
    op.drop_index(op.f('ix_stock_adjustments_adjustment_date'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_warehouse_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stocktake_items_part_id'), table_name='stocktake_items')
    op.drop_index(op.f('ix_stocktake_items_stocktake_id'), table_name='stocktake_items')
    op.drop_constraint(op.f('stocktake_items_stocktake_id_fkey'), 'stocktake_items', type_='foreignkey')
    op.create_foreign_key(None, 'stocktake_items', 'stocktakes', ['stocktake_id'], ['id'])
    op.alter_column('stocktakes', 'status',
               existing_type=postgresql.ENUM('planned', 'in_progress', 'completed', 'cancelled', name='stocktakestatus'),
               type_=sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='stocktakestatusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'planned'::stocktakestatus"))
    op.drop_index(op.f('ix_stocktakes_scheduled_date'), table_name='stocktakes')
    op.drop_index(op.f('ix_stocktakes_status'), table_name='stocktakes')
    op.drop_index(op.f('ix_stocktakes_warehouse_id'), table_name='stocktakes')
    op.drop_index(op.f('idx_support_videos_category'), table_name='support_videos')
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('creation', 'transfer', 'consumption', 'adjustment', name='transactiontype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_transactions_date'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_part'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_warehouse'), table_name='transactions')
    op.create_foreign_key(None, 'transactions', 'customer_orders', ['customer_order_id'], ['id'])
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_org_role'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_invited_by_user_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'pending_email')
    op.drop_column('users', 'preferred_country')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'localization_preferences')
    op.drop_column('users', 'invited_by_user_id')
    op.drop_constraint(op.f('warehouses_organization_id_name_key'), 'warehouses', type_='unique')
    op.drop_column('warehouses', 'contact_person')
    op.drop_column('warehouses', 'address')
    op.drop_column('warehouses', 'capacity_limit')
    op.drop_column('warehouses', 'email')
    op.drop_column('warehouses', 'phone')
    op.drop_column('warehouses', 'warehouse_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('warehouse_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('capacity_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('warehouses_organization_id_name_key'), 'warehouses', ['organization_id', 'name'], postgresql_nulls_not_distinct=False)
    op.add_column('users', sa.Column('invited_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('localization_preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_country', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pending_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_invited_by_user_id_fkey'), 'users', 'users', ['invited_by_user_id'], ['id'])
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_org_role'), 'users', ['organization_id', 'role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_index(op.f('idx_transactions_warehouse'), 'transactions', ['from_warehouse_id', 'to_warehouse_id'], unique=False)
    op.create_index(op.f('idx_transactions_part'), 'transactions', ['part_id'], unique=False)
    op.create_index(op.f('idx_transactions_date'), 'transactions', ['transaction_date'], unique=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('creation', 'transfer', 'consumption', 'adjustment', name='transactiontype'),
               existing_nullable=False)
    op.create_index(op.f('idx_support_videos_category'), 'support_videos', ['category'], unique=False)
    op.create_index(op.f('ix_stocktakes_warehouse_id'), 'stocktakes', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_stocktakes_status'), 'stocktakes', ['status'], unique=False)
    op.create_index(op.f('ix_stocktakes_scheduled_date'), 'stocktakes', ['scheduled_date'], unique=False)
    op.alter_column('stocktakes', 'status',
               existing_type=sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='stocktakestatusenum'),
               type_=postgresql.ENUM('planned', 'in_progress', 'completed', 'cancelled', name='stocktakestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'planned'::stocktakestatus"))
    op.drop_constraint(None, 'stocktake_items', type_='foreignkey')
    op.create_foreign_key(op.f('stocktake_items_stocktake_id_fkey'), 'stocktake_items', 'stocktakes', ['stocktake_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_stocktake_items_stocktake_id'), 'stocktake_items', ['stocktake_id'], unique=False)
    op.create_index(op.f('ix_stocktake_items_part_id'), 'stocktake_items', ['part_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_warehouse_id'), 'stock_adjustments', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_adjustment_date'), 'stock_adjustments', ['adjustment_date'], unique=False)
    op.create_index(op.f('ix_stock_adjustment_items_stock_adjustment_id'), 'stock_adjustment_items', ['stock_adjustment_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustment_items_part_id'), 'stock_adjustment_items', ['part_id'], unique=False)
    op.drop_constraint(None, 'security_events', type_='foreignkey')
    op.create_index(op.f('ix_protocol_translations_protocol_id'), 'protocol_translations', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_protocol_translations_language_code'), 'protocol_translations', ['language_code'], unique=False)
    op.create_index(op.f('idx_checklist_protocol'), 'protocol_checklist_items', ['protocol_id', 'item_order'], unique=False)
    op.alter_column('protocol_checklist_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('protocol_checklist_items', 'item_type',
               existing_type=sa.Enum('check', 'service', 'replacement', name='checklistitemtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('parts', sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('supplier_part_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('weight', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('dimensions', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('part_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('warranty_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('parts_part_number_key'), 'parts', ['part_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_parts_type_proprietary'), 'parts', ['part_type', 'is_proprietary'], unique=False)
    op.create_index(op.f('idx_parts_part_number'), 'parts', ['part_number'], unique=False)
    op.create_index(op.f('idx_parts_name_fulltext'), 'parts', [sa.literal_column("to_tsvector('english'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_parts_manufacturer'), 'parts', ['manufacturer'], unique=False, postgresql_where='(manufacturer IS NOT NULL)')
    op.alter_column('parts', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index(op.f('idx_part_videos_part_id'), 'part_videos', ['part_id'], unique=False)
    op.drop_constraint(None, 'part_order_items', type_='foreignkey')
    op.create_index(op.f('unique_oraseas_ee'), 'organizations', ['organization_type'], unique=True, postgresql_where="(organization_type = 'oraseas_ee'::organizationtype)")
    op.create_index(op.f('unique_bossaqua'), 'organizations', ['organization_type'], unique=True, postgresql_where="(organization_type = 'bossaqua'::organizationtype)")
    op.create_unique_constraint(op.f('organizations_name_key'), 'organizations', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_organizations_name'), 'organizations', ['name'], unique=False)
    op.alter_column('organizations', 'country',
               existing_type=sa.Enum('GR', 'UK', 'NO', 'CA', 'NZ', 'TR', 'OM', 'ES', 'CY', 'SA', 'KSA', name='countrycode'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_index(op.f('idx_reminder_machine_status'), 'maintenance_reminders', ['machine_id', 'status'], unique=False)
    op.create_index(op.f('idx_reminder_due_hours'), 'maintenance_reminders', ['due_hours', 'status'], unique=False)
    op.alter_column('maintenance_reminders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_reminders', 'acknowledged_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('maintenance_reminders', 'status',
               existing_type=sa.Enum('pending', 'acknowledged', 'completed', 'dismissed', name='reminderstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_index(op.f('idx_protocol_type_model'), 'maintenance_protocols', ['protocol_type', 'machine_model'], unique=False)
    op.alter_column('maintenance_protocols', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_protocols', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_protocols', 'protocol_type',
               existing_type=sa.Enum('daily', 'weekly', 'scheduled', 'custom', name='protocoltype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_execution_machine'), 'maintenance_executions', ['machine_id', 'performed_date'], unique=False)
    op.alter_column('maintenance_executions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_executions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_executions', 'status',
               existing_type=sa.Enum('scheduled', 'in_progress', 'completed', 'partial', 'skipped', name='maintenanceexecutionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('maintenance_executions', 'performed_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'maintenance_checklist_completions', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_checklist_completions_checklist_item_id_fkey'), 'maintenance_checklist_completions', 'protocol_checklist_items', ['checklist_item_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('maintenance_checklist_completions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_checklist_completions', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('machines', sa.Column('next_service_due', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('current_hours', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('last_maintenance_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('installation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('maintenance_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('hours_since_maintenance', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('warranty_expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('operational_status', sa.VARCHAR(length=50), server_default=sa.text("'running'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('maintenance_status', sa.VARCHAR(length=50), server_default=sa.text("'up_to_date'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('max_operating_hours', sa.INTEGER(), server_default=sa.text('10000'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('maintenance_interval_days', sa.INTEGER(), server_default=sa.text('90'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('last_service_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('maintenance_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('technician_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('machine_status', sa.VARCHAR(length=50), server_default=sa.text("'operational'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('operator_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('total_operating_hours', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('year_manufactured', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('machine_condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('manufacturer', sa.VARCHAR(length=255), server_default=sa.text("'BossAqua'::character varying"), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('service_interval_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('next_maintenance_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('machines', sa.Column('machine_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_machines_customer'), 'machines', ['customer_organization_id'], unique=False)
    op.drop_constraint(None, 'machine_maintenance', type_='foreignkey')
    op.drop_constraint(None, 'machine_maintenance', type_='foreignkey')
    op.drop_constraint(None, 'machine_hours', type_='foreignkey')
    op.drop_constraint(None, 'invitation_audit_logs', type_='foreignkey')
    op.create_unique_constraint(op.f('inventory_warehouse_id_part_id_key'), 'inventory', ['warehouse_id', 'part_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_inventory_warehouse_part'), 'inventory', ['warehouse_id', 'part_id'], unique=False)
    op.alter_column('customer_orders', 'shipped_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('ix_checklist_translations_language_code'), 'checklist_item_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_checklist_translations_item_id'), 'checklist_item_translations', ['checklist_item_id'], unique=False)
    op.drop_constraint(None, 'ai_sessions', type_='foreignkey')
    op.drop_constraint(None, 'ai_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_sessions_user_id_fkey'), 'ai_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ai_sessions_machine_id_fkey'), 'ai_sessions', 'machines', ['machine_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_ai_sessions_user_id'), 'ai_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_ai_sessions_updated_at'), 'ai_sessions', ['updated_at'], unique=False)
    op.create_index(op.f('idx_ai_sessions_status'), 'ai_sessions', ['status'], unique=False)
    op.create_index(op.f('idx_ai_sessions_machine_id'), 'ai_sessions', ['machine_id'], unique=False)
    op.create_index(op.f('idx_ai_sessions_created_at'), 'ai_sessions', ['created_at'], unique=False)
    op.alter_column('ai_sessions', 'status',
               existing_type=sa.Enum('active', 'completed', 'escalated', 'abandoned', name='aisessionstatus'),
               type_=postgresql.ENUM('active', 'completed', 'escalated', 'abandoned', name='ai_session_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::ai_session_status"))
    op.create_index(op.f('idx_ai_messages_session_id'), 'ai_messages', ['session_id'], unique=False)
    op.create_index(op.f('idx_ai_messages_sender'), 'ai_messages', ['sender'], unique=False)
    op.create_index(op.f('idx_ai_messages_created_at'), 'ai_messages', ['created_at'], unique=False)
    op.alter_column('ai_messages', 'message_type',
               existing_type=sa.Enum('text', 'voice', 'image', 'diagnostic_step', 'escalation', name='aimessagetype'),
               type_=postgresql.ENUM('text', 'voice', 'image', 'diagnostic_step', 'escalation', name='ai_message_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'text'::ai_message_type"))
    op.alter_column('ai_messages', 'sender',
               existing_type=sa.Enum('user', 'assistant', 'system', name='aimessagesender'),
               type_=postgresql.ENUM('user', 'assistant', 'system', name='ai_message_sender'),
               existing_nullable=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chunk_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('machine_models', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='knowledge_documents_pkey'),
    sa.UniqueConstraint('file_hash', name='knowledge_documents_file_hash_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_knowledge_documents_updated_at'), 'knowledge_documents', ['updated_at'], unique=False)
    op.create_index(op.f('idx_knowledge_documents_type'), 'knowledge_documents', ['document_type'], unique=False)
    op.create_index(op.f('idx_knowledge_documents_tags'), 'knowledge_documents', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_knowledge_documents_machine_models'), 'knowledge_documents', ['machine_models'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_knowledge_documents_language'), 'knowledge_documents', ['language'], unique=False)
    op.create_index(op.f('idx_knowledge_documents_created_at'), 'knowledge_documents', ['created_at'], unique=False)
    op.create_table('escalation_triggers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trigger_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('escalation_decision', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decision_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.session_id'], name=op.f('escalation_triggers_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('escalation_triggers_pkey'))
    )
    op.create_index(op.f('idx_escalation_triggers_type'), 'escalation_triggers', ['trigger_type'], unique=False)
    op.create_index(op.f('idx_escalation_triggers_triggered_at'), 'escalation_triggers', ['triggered_at'], unique=False)
    op.create_index(op.f('idx_escalation_triggers_session_id'), 'escalation_triggers', ['session_id'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('embedding_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_chunk', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.REAL()), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('embedding_id', name=op.f('document_embeddings_pkey'))
    )
    op.create_index(op.f('idx_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.create_index(op.f('idx_document_embeddings_chunk_index'), 'document_embeddings', ['chunk_index'], unique=False)
    op.create_table('expert_knowledge',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expert_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('problem_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('machine_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expert_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('expert_knowledge_pkey'))
    )
    op.create_index(op.f('idx_expert_knowledge_verified'), 'expert_knowledge', ['verified'], unique=False)
    op.create_index(op.f('idx_expert_knowledge_machine_version'), 'expert_knowledge', ['machine_version'], unique=False)
    op.create_index(op.f('idx_expert_knowledge_created_at'), 'expert_knowledge', ['created_at'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('escalation_reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('machine_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expert_contact_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assigned_expert_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.session_id'], name=op.f('support_tickets_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('support_tickets_pkey')),
    sa.UniqueConstraint('ticket_number', name=op.f('support_tickets_ticket_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('idx_support_tickets_session_id'), 'support_tickets', ['session_id'], unique=False)
    op.create_index(op.f('idx_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
    op.create_index(op.f('idx_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_table('inventory_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_type', postgresql.ENUM('low_stock', 'stockout', 'expiring', 'expired', 'excess', 'discrepancy', name='inventoryalerttype'), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', 'critical', name='inventoryalertseverity'), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('inventory_alerts_part_id_fkey')),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('inventory_alerts_resolved_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('inventory_alerts_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_alerts_pkey'))
    )
    op.create_index(op.f('ix_inventory_alerts_warehouse_id'), 'inventory_alerts', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_severity'), 'inventory_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_part_id'), 'inventory_alerts', ['part_id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_is_active'), 'inventory_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_alert_type'), 'inventory_alerts', ['alert_type'], unique=False)
    op.create_table('stock_adjustments_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('inventory_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('adjustment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('quantity_adjusted', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('reason_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('document_chunks_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.create_index(op.f('idx_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('expert_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('expert_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feedback_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggested_improvement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('expert_feedback_rating_check')),
    sa.ForeignKeyConstraint(['message_id'], ['ai_messages.message_id'], name=op.f('expert_feedback_message_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.session_id'], name=op.f('expert_feedback_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('expert_feedback_pkey'))
    )
    op.create_index(op.f('idx_expert_feedback_type'), 'expert_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('idx_expert_feedback_session_id'), 'expert_feedback', ['session_id'], unique=False)
    op.create_index(op.f('idx_expert_feedback_rating'), 'expert_feedback', ['rating'], unique=False)
    op.create_index(op.f('idx_expert_feedback_message_id'), 'expert_feedback', ['message_id'], unique=False)
    op.create_index(op.f('idx_expert_feedback_expert_user_id'), 'expert_feedback', ['expert_user_id'], unique=False)
    op.create_index(op.f('idx_expert_feedback_created_at'), 'expert_feedback', ['created_at'], unique=False)
    # ### end Alembic commands ###
