"""Add user language and localization preferences

Revision ID: 0203a54bc019
Revises: 0b12c647d983
Create Date: 2025-07-31 10:03:32.611918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0203a54bc019'
down_revision: Union[str, Sequence[str], None] = '0b12c647d983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_language', sa.String(length=5), server_default='en', nullable=True))
    op.add_column('users', sa.Column('preferred_country', sa.String(length=3), nullable=True))
    op.add_column('users', sa.Column('localization_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'localization_preferences')
    op.drop_column('users', 'preferred_country')
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###
