"""Add audit and security event tables

Revision ID: 8e7a2f17d68e
Revises: f15a2ee5a7b4
Create Date: 2025-07-31 11:16:22.943687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7a2f17d68e'
down_revision: Union[str, Sequence[str], None] = 'f15a2ee5a7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
